---
# Source: datahub/templates/kafka-setup-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-kafka-setup-job
  labels:
    helm.sh/chart: datahub-0.4.26
    app.kubernetes.io/name: datahub
    app.kubernetes.io/instance: vault
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
      containers:
        - name: kafka-setup-job
          image: docker.io/acryldata/datahub-kafka-setup:v0.14.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "prerequisites-zookeeper:2181"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "prerequisites-kafka:9092"
            - name: MAX_MESSAGE_BYTES
              value: "5242880"
            - name: USE_CONFLUENT_SCHEMA_REGISTRY
              value: "false"
            - name: METADATA_CHANGE_EVENT_NAME
              value: MetadataChangeEvent_v4
            - name: FAILED_METADATA_CHANGE_EVENT_NAME
              value: FailedMetadataChangeEvent_v4
            - name: METADATA_AUDIT_EVENT_NAME
              value: MetadataAuditEvent_v4
            - name: DATAHUB_USAGE_EVENT_NAME
              value: DataHubUsageEvent_v1
            - name: METADATA_CHANGE_PROPOSAL_TOPIC_NAME
              value: MetadataChangeProposal_v1
            - name: FAILED_METADATA_CHANGE_PROPOSAL_TOPIC_NAME
              value: FailedMetadataChangeProposal_v1
            - name: METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME
              value: MetadataChangeLog_Versioned_v1
            - name: METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME
              value: MetadataChangeLog_Timeseries_v1
            - name: PLATFORM_EVENT_TOPIC_NAME
              value: PlatformEvent_v1
            - name: DATAHUB_UPGRADE_HISTORY_TOPIC_NAME
              value: DataHubUpgradeHistory_v1
          securityContext:
            runAsUser: 1000
          volumeMounts:
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 300m
              memory: 768Mi
