---
# Source: datahub/templates/mysql-setup-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-mysql-setup-job
  labels:
    helm.sh/chart: datahub-0.4.26
    app.kubernetes.io/name: datahub
    app.kubernetes.io/instance: vault
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
spec:
  template:
    spec:
      volumes:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      containers:
        - name: mysql-setup-job
          image: docker.io/acryldata/datahub-mysql-setup:v0.14.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mysql-secrets"
                  key: "mysql-root-password"
            - name: MYSQL_HOST
              value: "prerequisites-mysql"
            - name: MYSQL_PORT
              value: "3306"
          securityContext:
            runAsUser: 1000
          volumeMounts:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
