apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
              value: "false"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_HEAP_OPTS
              value: -Xms256m -Xmx256m
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_MAX_MESSAGE_BYTES
              value: "5242880"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "5242880"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:7.4.0
          livenessProbe:
            exec:
              command:
                - nc -z broker ${DATAHUB_KAFKA_BROKER_PORT:-9092}
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 1
            timeoutSeconds: 5
          name: broker
          ports:
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: broker
      hostname: broker
      restartPolicy: Always
      volumes:
        - name: broker
          persistentVolumeClaim:
            claimName: broker
