apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datahub-gms
  name: datahub-gms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datahub-gms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: datahub-gms
    spec:
      containers:
        - env:
            - name: DATAHUB_SERVER_TYPE
              value: quickstart
            - name: DATAHUB_TELEMETRY_ENABLED
              value: "true"
            - name: DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID
              value: generic-duhe-consumer-job-client-gms
            - name: EBEAN_DATASOURCE_DRIVER
              value: com.mysql.jdbc.Driver
            - name: EBEAN_DATASOURCE_HOST
              value: mysql:3306
            - name: EBEAN_DATASOURCE_PASSWORD
              value: datahub
            - name: EBEAN_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
            - name: EBEAN_DATASOURCE_USERNAME
              value: datahub
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX
              value: "true"
            - name: ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX
              value: "true"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ENTITY_REGISTRY_CONFIG_PATH
              value: /datahub/datahub-gms/resources/entity-registry.yml
            - name: ENTITY_SERVICE_ENABLE_RETENTION
              value: "true"
            - name: ES_BULK_REFRESH_POLICY
              value: WAIT_UNTIL
            - name: GRAPH_SERVICE_DIFF_MODE_ENABLED
              value: "true"
            - name: GRAPH_SERVICE_IMPL
              value: elasticsearch
            - name: JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: KAFKA_BOOTSTRAP_SERVER
              value: broker:29092
            - name: KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR
              value: "true"
            - name: KAFKA_SCHEMAREGISTRY_URL
              value: http://schema-registry:8081
            - name: MAE_CONSUMER_ENABLED
              value: "true"
            - name: MCE_CONSUMER_ENABLED
              value: "true"
            - name: PE_CONSUMER_ENABLED
              value: "true"
            - name: UI_INGESTION_ENABLED
              value: "true"
          image: acryldata/datahub-gms:head
          livenessProbe:
            exec:
              command:
                - curl -sS --fail http://datahub-gms:8080/health
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 1
            timeoutSeconds: 5
          name: datahub-gms
          ports:
            - containerPort: 8080
              protocol: TCP
      hostname: datahub-gms
      restartPolicy: Always
