---
# Source: datahub/charts/acryl-datahub-actions/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-acryl-datahub-actions
  labels:
    helm.sh/chart: acryl-datahub-actions-0.2.147
    app.kubernetes.io/name: acryl-datahub-actions
    app.kubernetes.io/instance: vault
    app.kubernetes.io/version: "0.0.11"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acryl-datahub-actions
      app.kubernetes.io/instance: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acryl-datahub-actions
        app.kubernetes.io/instance: vault
    spec:
      terminationGracePeriodSeconds: 150
      serviceAccountName: default
      securityContext:
        {}
      volumes:
      initContainers:
      containers:
        - name: acryl-datahub-actions
          securityContext:
            {}
          image: docker.io/acryldata/datahub-actions:v0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          env:
            - name: DATAHUB_GMS_PROTOCOL
              value: http
            - name: DATAHUB_GMS_HOST
              value: vault-datahub-gms
            - name: DATAHUB_GMS_PORT
              value: "8080"
            # Deprecated in favour of DATAHUB_* variables
            - name: GMS_HOST
              value: vault-datahub-gms
            - name: GMS_PORT
              value: "8080"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "prerequisites-kafka:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://vault-datahub-gms:8080/schema-registry/api/"
            - name: KAFKA_AUTO_OFFSET_POLICY
              value: "latest"
            - name: METADATA_CHANGE_EVENT_NAME
              value: MetadataChangeEvent_v4
            - name: FAILED_METADATA_CHANGE_EVENT_NAME
              value: FailedMetadataChangeEvent_v4
            - name: METADATA_AUDIT_EVENT_NAME
              value: MetadataAuditEvent_v4
            - name: DATAHUB_USAGE_EVENT_NAME
              value: DataHubUsageEvent_v1
            - name: METADATA_CHANGE_PROPOSAL_TOPIC_NAME
              value: MetadataChangeProposal_v1
            - name: FAILED_METADATA_CHANGE_PROPOSAL_TOPIC_NAME
              value: FailedMetadataChangeProposal_v1
            - name: METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME
              value: MetadataChangeLog_Versioned_v1
            - name: METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME
              value: MetadataChangeLog_Timeseries_v1
            - name: PLATFORM_EVENT_TOPIC_NAME
              value: PlatformEvent_v1
            - name: DATAHUB_SYSTEM_CLIENT_ID
              value: __datahub_system
            - name: DATAHUB_SYSTEM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: datahub-auth-secrets
                  key: system_client_secret
          volumeMounts:
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
