---
# Source: datahub/charts/acryl-datahub-actions/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-acryl-datahub-actions
  labels:
    helm.sh/chart: acryl-datahub-actions-0.2.147
    app.kubernetes.io/name: acryl-datahub-actions
    app.kubernetes.io/instance: vault
    app.kubernetes.io/version: "0.0.11"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: acryl-datahub-actions
    app.kubernetes.io/instance: vault
