apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datahub_setup_job: "true"
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: elasticsearch-setup
  name: elasticsearch-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch-setup
  template:
    metadata:
      annotations:
        datahub_setup_job: "true"
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: elasticsearch-setup
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_PROTOCOL
              value: http
            - name: ELASTICSEARCH_USE_SSL
              value: "false"
            - name: USE_AWS_ELASTICSEARCH
              value: "false"
          image: acryldata/datahub-elasticsearch-setup:head
          name: elasticsearch-setup
      hostname: elasticsearch-setup
      restartPolicy: Always
