apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datahub_setup_job: "true"
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-setup
  name: kafka-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-setup
  template:
    metadata:
      annotations:
        datahub_setup_job: "true"
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-setup
    spec:
      containers:
        - env:
            - name: DATAHUB_PRECREATE_TOPICS
              value: "false"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: broker:29092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: USE_CONFLUENT_SCHEMA_REGISTRY
              value: "TRUE"
          image: acryldata/datahub-kafka-setup:head
          name: kafka-setup
      hostname: kafka-setup
      restartPolicy: Always
