apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datahub_setup_job: "true"
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql-setup
  name: mysql-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-setup
  template:
    metadata:
      annotations:
        datahub_setup_job: "true"
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql-setup
    spec:
      containers:
        - env:
            - name: DATAHUB_DB_NAME
              value: datahub
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: datahub
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: datahub
          image: acryldata/datahub-mysql-setup:head
          name: mysql-setup
      hostname: mysql-setup
      restartPolicy: Always
