apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: schema-registry
    spec:
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemaregistry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT
          image: confluentinc/cp-schema-registry:7.4.0
          livenessProbe:
            exec:
              command:
                - nc -z schema-registry 8081
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 1
            timeoutSeconds: 5
          name: schema-registry
          ports:
            - containerPort: 8081
              protocol: TCP
      hostname: schema-registry
      restartPolicy: Always
