apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-without-neo4j.quickstart.yml convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:7.4.0
          livenessProbe:
            exec:
              command:
                - echo srvr | nc zookeeper ${DATAHUB_ZK_PORT:-2181}
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: zookeeper
          ports:
            - containerPort: 2181
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/zookeeper/data
              name: zkdata
            - mountPath: /var/lib/zookeeper/log
              name: zklogs
      hostname: zookeeper
      restartPolicy: Always
      volumes:
        - name: zkdata
          persistentVolumeClaim:
            claimName: zkdata
        - name: zklogs
          persistentVolumeClaim:
            claimName: zklogs
