apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.quickstart.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.quickstart.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4JLABS_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_AUTH
              value: neo4j/datahub
            - name: NEO4J_dbms_allow__upgrade
              value: "true"
            - name: NEO4J_dbms_default__database
              value: graph.db
          image: neo4j:4.4.9-community
          livenessProbe:
            exec:
              command:
                - wget http://neo4j:${DATAHUB_NEO4J_HTTP_PORT:-7474}
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
          name: neo4j
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: neo4jdata
      hostname: neo4j
      restartPolicy: Always
      volumes:
        - name: neo4jdata
          persistentVolumeClaim:
            claimName: neo4jdata
