apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: neo4jdata
  name: neo4jdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
