---
# Source: datahub/charts/datahub-frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-datahub-frontend
  labels:
    helm.sh/chart: datahub-frontend-0.2.159
    app.kubernetes.io/name: datahub-frontend
    app.kubernetes.io/instance: vault
    app.kubernetes.io/version: "v0.13.1"
    app.kubernetes.io/managed-by: Helm
